apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: public.ecr.aws/nginx/nginx:1.27.1
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: kargo-demo
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: kargo-demo
