---
# Source: kargo-demo/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kargo-demo
  labels:
    helm.sh/chart: kargo-demo-0.1.0
    app.kubernetes.io/name: kargo-demo
    app.kubernetes.io/instance: kargo-demo
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: kargo-demo
    app.kubernetes.io/instance: kargo-demo
